Local
wayungi/budget_app pull request #2
Opened 2022-11-23 21:29 UTC by wayungi

## This PR  adds the following features 💯 

### Interactions 👍🏾 

#### Splash screen 😄 
- A simple page with the name of your app (yes, you need to choose one).
- Links to the signup and login pages.

#### Sign up and login pages 😃 
- The user should be able to register in the app with full name, email and password (all mandatory).
- The user can log into the app using email and password.
- If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

#### Home page (categories page) 🏠 
- When the user logs in, they are presented with the categories page 📄 
- For each category, the user can see their name, icon and the total amount of all the transactions that belong to that category.
- When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
- There is a button  "add a new category" at the bottom that brings the user to the page to create a new category.

#### Transactions page 💵 
- For a given category, the list of transactions is presented, ordered by the most recent.
- At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

#### Add a new category page 📃 
- The user fills out a form to create a new category, indicating their name and icon (both mandatory) 📃  ✍🏾 
- The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success. 💾 
- When the user clicks on the "Back" button (<), the user navigates to the home page. 🔙 

### Add a new transaction page
 - The user fills out a form to create a new transaction with:
   - name (mandatory) 📛 
   - amount (mandatory) 🤑 
   - categories (mandatory at least one) 👥 
- The user clicks (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
- When the user clicks on the ◀️  "Back" button (<), the user navigates to the transactions page for that category.

### Testing requirements 
- Create unit and integration tests for all the most important components of your RoR application.

2022-11-24 07:29 UTC, prolajumokeoni commented
Hi @wayungi, Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, this is a requirement to get a review

2022-11-24 07:32 UTC, prolajumokeoni commented
Hi @wayungi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that  does not have the updated readme, Kindly use the updated version of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-25 15:30 UTC, FrederickMih requested changes
Hi @wayungi, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights :green_circle: 

- Users inputs have been validated :+1: 
- Both Home and Transaction pages have been added :+1: 
- PR is professional :+1: 


## Suggested changes

- [ ] Hi @wayungi, let's kindly follow the design guidelines for this project: Colors, typography, and layout should be exactly the same.

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-25 15:30 UTC, FrederickMih commented on README.md
> +- [Live Demo Link](https://rocky-plateau-40125.herokuapp.com/)
- [x] Hi @wayungi, let's kindly make sure that our project is deployed properly. Your deployment project should work like the local one.

2022-11-25 15:30 UTC, FrederickMih commented on app/views/expenses/_expense.html.erb
> +    <td><%= expense.amount %></td>
- [**Optional**]  What do you think of prefixing the currency sign as you have done for the total amount of all the transactions(expenses) that belong to each category?

2022-11-25 15:30 UTC, FrederickMih commented on app/views/categories/index.html.erb
> +    <%= link_to "New category", new_category_path, class:'new_category'%>
- [ ] Hi @wayungi, based on the requirements of this project, this should be a button and should be positioned at the bottom. Please let's kindly fix it to make sure that our project matches the original design.

2022-11-25 15:30 UTC, FrederickMih commented on app/views/expenses/_expense.html.erb
> +    <td><%= expense.amount %></td>
- [**Optional**] I think it's also important to include the date of creation of each expense. This will better track the date of creation of each expense.

2022-11-25 15:30 UTC, FrederickMih commented on app/views/expenses/index.html.erb
> +    <%= link_to "Add new expense", new_category_expense_path(@category), class:'new_expense blue'%><br />
- [x] As already mentioned above, this should be a button and should be positioned at the bottom of the page.

2022-11-25 15:30 UTC, FrederickMih commented on app/views/expenses/index.html.erb
> +    <%= link_to "Home page", categories_path, class:'back_to_categories blue' %>
- [x] Please it's important to work in line with the design guidelines. This link should be placed as seen on the original design.

2022-11-25 15:30 UTC, FrederickMih commented on app/views/categories/new.html.erb
> +  <h1>New category</h1>
- [x] Let's kindly work with the design guidelines.

2022-11-25 15:30 UTC, FrederickMih commented on app/views/categories/new.html.erb
> +  <%= link_to "Back to categories", categories_path, class:'back_to_category' %>
- [x] Kindly refer to the comment above.

2022-11-25 15:30 UTC, FrederickMih commented on app/views/expenses/new.html.erb
> +  <%= link_to "Back", category_expenses_path(@category), class:'back_to_category' %>
- [x] Kindly refer to the comments above.

2022-11-25 15:30 UTC, FrederickMih commented on config/routes.rb
> +  end
- [ ] Let's kindly use only the necessary routes in this project. As you can see in the screenshot below, some routes are not used.


![Screenshot from 2022-11-25 16-14-17](https://user-images.githubusercontent.com/63087491/204014321-f7d7dae3-730b-47ed-bf91-c8443b6cb0bb.png)

2022-11-25 15:30 UTC, FrederickMih commented on app/controllers/categories_controller.rb
>    def update
- [Optional] You are not making use of the update and destroy actions, let's better get rid of it.

2022-11-25 16:26 UTC, wayungi commented on app/views/expenses/_expense.html.erb
> +    <td><%= expense.amount %></td>
@FrederickMih great suggestion. working on it

2022-11-25 17:17 UTC, wayungi commented on app/views/categories/index.html.erb
> +    <%= link_to "New category", new_category_path, class:'new_category'%>
@FrederickMih, this has been resolved as requested

2022-11-25 17:25 UTC, wayungi commented on app/views/expenses/_expense.html.erb
> +    <td><%= expense.amount %></td>
resolved

2022-11-25 19:43 UTC, wayungi commented on README.md
> +- [Live Demo Link](https://rocky-plateau-40125.herokuapp.com/)
New changes updated

2022-11-25 20:53 UTC, KDlamini approved these changes
### Hi @wayungi 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ Professional pull request
✔️ App follows design specifications
✔️ All required functionalities work as expected
✔️ No linter errors

# Status: Approved ✔️ 

![oscars-standing-ovation](https://user-images.githubusercontent.com/38088818/164766743-7f6493f3-4506-4331-9678-207bad27e7f5.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 22:43 UTC, merged